mv gamepal3.cpp gamepal3.c
mv id_ca.cpp id_ca.c
mv id_in.cpp id_in.c
mv id_pm.cpp id_pm.c
mv id_sd.cpp id_sd.c
mv id_us_1.cpp id_us_1.c
mv id_vh.cpp id_vh.c
mv id_vl.cpp id_vl.c
mv signon.cpp signon.c
mv wl_act1.cpp wl_act1.c
mv wl_act2.cpp wl_act2.c
mv wl_agent.cpp wl_agent.c
mv wl_debug.cpp wl_debug.c
mv wl_draw.cpp wl_draw.c
mv wl_game.cpp wl_game.c
mv wl_inter.cpp wl_inter.c
mv wl_main.cpp wl_main.c
mv wl_menu.cpp wl_menu.c
mv wl_play.cpp wl_play.c
mv wl_state.cpp wl_state.c
mv wl_text.cpp wl_text.c
